/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2022-08-16 05:26:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jspSY;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.sns.dao.*;
import com.sns.dto.*;
import java.util.*;
import java.sql.*;
import com.sns.dao.*;
import com.sns.dto.*;
import java.util.*;
import java.sql.*;
import com.sns.dao.*;
import com.sns.dto.*;
import java.util.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jspSY/TrendRankModule.jspf", Long.valueOf(1659593972597L));
    _jspx_dependants.put("/jspSY/ModuleMenu.jspf", Long.valueOf(1659593972554L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("com.sns.dao");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.sns.dto");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	

	int loginID = (Integer)(session.getAttribute("profileId")); 
	/* int userID =1;//세션아이디와 같음 */
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Home</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"main.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"modal.css\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/6ebfb758c0.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    \tvar loginID = '");
      out.print((Integer)(session.getAttribute("profileId")));
      out.write("'; /* 전역변수로 만들어서 js.에서 변수 사용  */\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"../js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\t<script src=\"../js/common-sy.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<body style=\"margin: 0 auto; background-color: #141414; color: #ffffff\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
    int loginId = (Integer)(session.getAttribute("profileId")); 	 
	PostViewDAO postViewDao = new PostViewDAO();	

	ArrayList<ProfileDTO> profileList = postViewDao.viewProfile(loginId);
			
		for(ProfileDTO profile : profileList) {

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"../js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function (){\r\n");
      out.write("\t\t\t$(\".menu-box2\").click(function (){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"background_btm\" style=\"display: none;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal Dialogs -->\r\n");
      out.write("\t<div id=\"postModal\">\r\n");
      out.write("\t\t<div id=\"post-box\" class=\"modal-stl\"\r\n");
      out.write("\t\t\tstyle=\"display: none; background-color: #282828;\">\r\n");
      out.write("\t\t\t<div class=\"profile-imgbox\">\r\n");
      out.write("\t\t\t\t<div class=\"box\" style=\"background: #141414\">\r\n");
      out.write("\t\t\t\t\t<img class=\"profile\" src=\"../images/");
      out.print(profile.getProfileImg());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t");
  }  
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"post-container\">\r\n");
      out.write("\t\t\t\t<div class=\"post-container2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"postingbox\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action=\"../FileUploadServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"autosize\" onkeydown=\"resize(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonkeyup=\"resize(this)\" name=\"content\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"무슨 일이 일어나고 있나요?\" style=\"background-color:#282828\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t                function resize(obj) {\r\n");
      out.write("\t\t\t\t\t\t                  obj.style.height = \"1px\";\r\n");
      out.write("\t\t\t\t\t\t                  obj.style.height = (12+obj.scrollHeight)+\"px\";\r\n");
      out.write("\t\t\t\t\t\t                }\r\n");
      out.write("\t\t\t\t\t\t                </script>\r\n");
      out.write("\t\t\t\t\t\t                <input type=\"file\" name=\"file\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"posting-bottom \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"ps-button postButton\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"posting\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: transparent; color: white; border: none; font-size: 20px; line-height: 19px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 댓글 모달창 -->\r\n");
      out.write("\t<div class=\"modal-commBox\">\r\n");
      out.write("\t\t<div class=\"comm-box modal-stl\"\r\n");
      out.write("\t\t\tstyle=\"display: none; background-color: #282828;\">\r\n");
      out.write("\t\t\t<div class=\"profile-imgbox\">\r\n");
      out.write("\t\t\t\t<div class=\"box\" style=\"background: #141414\">\r\n");
      out.write("\t\t\t\t\t");

			
			for(ProfileDTO profile : profileList) {
	
 			 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<img class=\"profile\" src=\"../images/");
      out.print(profile.getProfileImg());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"post-container\">\r\n");
      out.write("\t\t\t\t<div class=\"post-container2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"postingbox\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"CommentsAct.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"autosize\" onkeydown=\"resize(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonkeyup=\"resize(this)\" placeholder=\"포스팅에 대한 당신의 생각을 전하세요.\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"comments\" style=\"background-color: #282828;\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t                  function resize(obj) {\r\n");
      out.write("\t\t\t                    obj.style.height = \"1px\";\r\n");
      out.write("\t\t\t                    obj.style.height = 12 + obj.scrollHeight + \"px\";\r\n");
      out.write("\t\t\t                  }\r\n");
      out.write("\t\t\t                </script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"post_id\" id=\"hidden_bno\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"posting-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ps-button postButton\" !important\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px 10px; margin-left: 380px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"답글\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"border: none; outline: none;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<!-------------------- 좌측 메뉴바--------------- -->\r\n");
      out.write("\t\t<div class=\"menu-container\">\r\n");
      out.write("\t\t\t<div class=\"imagebox imgButton\">\r\n");
      out.write("\t\t\t\t<img style=\"cursor:pointer;\" src=\"../images/netflix1.png \" !important style=\"margin: 0\"\r\n");
      out.write("\t\t\t\t\tonClick=\"location.href='../jspUJ/index.jsp?profile_id=");
      out.print(loginId );
      out.write("'\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menu-box1 menuButton\" onClick=\"location.href='Main.jsp'\">\r\n");
      out.write("\t\t\t\t<i class=\"fa-solid fa-house\"></i><span>&nbsp;&nbsp; 홈</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"meun-box2\" class=\"menu-box2 menuButton\" onClick=\"location.href='Trend.jsp'\">\r\n");
      out.write("\t\t\t\t<i class=\"fa-solid fa-hashtag\"></i><span>&nbsp;&nbsp; 탐색하기</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menu-box3 menuButton\" onClick=\"location.href='Notice.jsp'\"> \r\n");
      out.write("\t\t\t\t<i class=\"fa-solid fa-bell\"></i> <span>&nbsp;&nbsp; 알림</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menu-box4 menuButton\"\r\n");
      out.write("\t\t\t\tonClick=\"location.href='Message.jsp'\">\r\n");
      out.write("\t\t\t\t<i class=\"fa-solid fa-envelope\"></i><span>&nbsp;&nbsp; 쪽지</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menu-box5 menuButton\" onClick=\"location.href='Profile.jsp?&profile_id=");
      out.print(loginId);
      out.write("'\"> \r\n");
      out.write("\t\t\t\t<i class=\"fa-solid fa-user\"></i><span>&nbsp;&nbsp; 프로필</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"modal-btn\" class=\"post-button postButton\">posting</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>");
      out.write("\r\n");
      out.write("    <main style=\"float:left\">\r\n");
      out.write("\t\t<div class=\"main-box\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"home-box1\" style=\"display:block\">\r\n");
      out.write("\t\t\t\t<div class=\"home-bar\"> <span style=\"font-weight: 800;\">홈</span></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 포스팅하기 -->\r\n");
      out.write("\t\t\t\t<div id=\"post-box-main\" style=\"overflow: hidden; height: auto;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile-imgbox\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\" style=\"background: #141414;\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								for(ProfileDTO profile : profileList) {
							
      out.write("\r\n");
      out.write("\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"profile\" src=\"../images/");
      out.print(profile.getProfileImg() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"post-container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-container2 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"postingbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"../FileUploadServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"loginID\" value=\"");
      out.print(loginId);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"autosize\" onkeydown=\"resize(this)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"resize(this)\" name=\"content\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"무슨 일이 일어나고 있나요?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction resize(obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobj.style.height = \"1px\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobj.style.height = (30+obj.scrollHeight)+\"px\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--  파일 업로드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"file\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"posting-bottom \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ps-button postButton\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"posting\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: transparent; color: white; border: none; font-size: 20px; line-height: 19px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--타임라인의 포스팅들 -->\r\n");
      out.write("\t\t\t");

				ArrayList<PostViewDTO> postList = postViewDao.timeLine(loginID);
					for(PostViewDTO post : postList) {
			
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class=\"article-box\" style=\"overflow: hidden; height: auto;\" bno=");
      out.print(post.getPostID());
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"post_id\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile-imgbox\" onclick=\"location.href ='Profile.jsp?profile_id=");
      out.print(post.getProfileID());
      out.write("'\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\" style=\"background: #141414;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"profile\" src=\"../images/");
      out.print(post.getProfileImg());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"namebar\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"spannickname\">");
      out.print(post.getNickname() );
      out.write(" &nbsp;</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"spanid\"> ");
      out.print(post.getWriteDate() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"postingbox\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href ='Posting.jsp?post_id=");
      out.print(post.getPostID());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(post.getContent() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 파일 업로드 내용이 있으면/없으면 -->\r\n");
      out.write("\t\t\t\t");
 
               		if(post.getImgFile() !=null) {
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/");
      out.print(post.getImgFile());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom-bar\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"div_bottombar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-message\"></i><span class=\"tab\"></span>\r\n");
      out.write("\t\t\t\t \t");
 
					 	if(postViewDao.likeIt(post.getPostID(),loginID )) {		
					 		
                    
      out.write("\r\n");
      out.write("                   \t\t<i class=\"fa-solid fa-heart\"></i>\r\n");
      out.write("                    ");
 	} else { 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("        \t\t            \t<i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("                    ");
 } 
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"heart_count\" style=\"font-size:13px\">");
      out.print(post.getLikeCnt());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tab\"></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-arrow-up-from-bracket\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t\t\r\n");
      out.write("         <!-- -----------------우측 트렌드 랭킹 바---------------------------- -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t<div id=\"trend-box\">\r\n");
      out.write("\t\t\t\t<div class=\"right-container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search-bar\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"TrendKeyword.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-magnifying-glass\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"float: left; line-height: 30px\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"keyword\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"float: left; width: 200px; background-color: #282828; border: none; color: white; margin-left: 10px; outline: none; font-size: 20px\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"trend-heading\">나를 위한 트렌드</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

    				
    		HashtagDAO hDao = new HashtagDAO();
    		ArrayList<HashtagDTO> hList = hDao.trendRank();
    			
    			for(HashtagDTO hashtag : hList){
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"trend-box trendButton \"\r\n");
      out.write("\t\t\t\tonclick=\"location.href='TrendKeyword.jsp?keyword=");
      out.print( hashtag.getHashtagName());
      out.write("'\">\r\n");
      out.write("\t\t\t\t<span class=\"trendspan\">");
      out.print(hashtag.getHashtagName() );
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t<span class=\"post_cnt\">");
      out.print(hashtag.getHashtagCnt() );
      out.write("개의 포스트</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"trend-plus trendButton\"\r\n");
      out.write("\t\t\t\tonClick=\"location.href='Trend.jsp'\">더 보기</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
